### ISSUE TITLE
Allow creation of "Private Clusters"

### ISSUE THREAD

**Issue by itspngu** [kubernetes-sigs/cluster-api-provider-gcp#903]
/kind feature

**Describe the solution you'd like**
Currently, CAPG is hard-wired to create GCE load balancing components with a public IP address for apiserver access. The nodes themselves do not receive public addresses unless explicitly configured as such, the same should apply to the apiserver's endpoint(s). Being able to provision clusters with access limited by private IP address connectivity would be beneficial for obvious reasons.

**Anything else you would like to add:**
I'm not 100% sure if using private endpoints should be the default - it'd be in line with how address management for nodes currently works, but would also have potential for being a breaking change.

The GKE-specific concept of private clusters is explained [here](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters). This feature request is scoped at allowing this to apply for both managed (GKE) and unmanaged (plain Cluster API) clusters.

**Comment by lreciomelero** [comment]
Hi folks! Is it possible to take a look at this feature?

**Comment by bfournie** [comment]
I believe this is resolved with https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1222 and subsequent changes.

**Comment by maxkokocom** [comment]
This issue and issue of private management cluster not able to communicate with newly created clusters (or maybe just not documented ticket) https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2484 still persist.

**Comment by RnkeZ** [comment]
@maxkokocom I believe the issue you mentioned is fixed by #1468
